# run this with the following command to test:
# docker-compose -f dockron.yml up --build
version: '3.7'

services:
  date-out:
    image: busybox
    command: >-
      sh -c "while true; do date; sleep 1; done"

  pulse:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - ./utils/docker.tcl:/opt/dockron/utils/docker.tcl:ro
    init: true
    command: >-
      -docker "unix:///var/run/docker.sock"
      -precision "seconds"
      -rules
        "
        0 * * * * * *date-out* restart \"\"
        15 * * * * * *date-out* \"\" \"%docker% restart %id%\"
        30 * * * * * *date-out* \"\" \"exec /usr/bin/docker container restart %name%\"
        45 * * * * * *date-out* \"\" \"@/opt/dockron/utils/docker.tcl container restart %name%\"
        "